### ISSUE TITLE
Add calendar view for date selection in forms

### ISSUE THREAD

**Issue by jfirwin** [federico-terzi/modulo#14]
It would be awesome to implement the [wxCalendarCtrl](https://docs.wxwidgets.org/3.0/classwx_calendar_ctrl.html) as a form option. I've been building some pretty complex forms for date selection that are good enough, but a calendar would be far superior.

For example:
```
matches:
  - trigger: ":select date"
    replace: "{{formatteddate}}"
    vars:
      - name: dates
        type: form
        params:
          layout: |
            {{days}}
          fields:
            days:
              type: list
              values:
                - Today
                - One week from Today
                - Monday
                - Tuesday
                - Wednesday
                - Thursday
                - Friday
                - Next Monday
                - Next Tuesday
                - Next Wednesday
                - Next Thursday
                - Next Friday
              default: "Today"
      - name: dateforward
        type: shell
        params:
          cmd: "echo `case $ESPANSO_DATES_DAYS in 'Monday') echo '-v +Mon' ;; 'Tuesday') echo '-v +Tue' ;; 'Wednesday') echo '-v +Wed' ;; 'Thursday') echo '-v +Thu' ;; 'Friday') echo '-v +Fri' ;; 'Next Monday') echo '-v +1w -v +Mon' ;; 'Next Tuesday') echo '-v +1w -v +Tue' ;; 'Next Wednesday') echo '-v +1w -v +Wed' ;; 'Next Thursday') echo '-v +1w -v +Thu' ;; 'Next Friday') echo '-v +1w -v +Fri' ;; 'Today') echo '' ;; 'One week from Today') echo '-v +7d'  ;; esac`"
      - name: newdate
        type: shell
        params:
          cmd: "echo `date $ESPANSO_DATEFORWARD +\"%A, %B %-d\"`"
      # Grabbing the ordinal date
      - name: day
        type: shell
        params:
          cmd: "echo `date $ESPANSO_DATEFORWARD +\"%-d\"`"
      - name: ordinal
        type: shell
        params:
          cmd: "case $ESPANSO_DAY in *1[0-9] | *[04-9]) echo th ;; *1) echo st ;; *2) echo nd ;; *3) echo rd ;; esac"
      - name: formatteddate
        type: shell
        params:
          cmd: "echo $ESPANSO_NEWDATE$ESPANSO_ORDINAL"
```
could be simplified to just:
```
matches:
  - trigger: ":selectdate"
    form: |
      {{selectdate}}
    form_fields:
      selectdate:
        type: calendar
          output_format: "%A, %B %-d"
```

**Note** I just realized my above example includes some tricky stuff for grabbing the ordinal date. I don't think that would necessarily be needed.
