### ISSUE TITLE
Allow set another field's name as default value

### ISSUE THREAD

**Issue by yihou** [federico-terzi/modulo#8]
Request for 1 enhancement feature as described in the title, below is the example use case:
```yml
layout: |
  Field1: {{field1}}, /n Field2: {{field2}}
fields:
  field2:
    default: {{field1}}
```

Not sure can it be done, hope I can help out, but I don't know Rust at the moment.

Million thanks to the plugin created, appreciate lots!!
